[package]
name = "thinker"
description = "RethinkDB driver"
version = "0.0.1"
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-rethinkdb/thinker"
documentation = "https://docs.rs/thinker"
readme = "README.md"
keywords = ["database", "rethinkdb", "reql", "driver"]
authors = ["rushmorem <rushmore@webenchanter.com>"]

build = "build.rs"

[dependencies]
ql2 = "1.0.0"
reql = { git = "https://github.com/rust-rethinkdb/reql" }
r2d2 = "0.7.0"
byteorder = "0.5.1"
bufstream = "0.1.1"
futures = "0.1"
tokio-core = "0.1"
slog = "1.0.0"
slog-term = "1.0.0"
serde = "0.8"
serde_json = "0.8"
lazy_static = "0.2.1"

[build-dependencies]
skeptic = "0.6.1"
serde_codegen = "0.8"

[dev-dependencies]
skeptic = "0.6.1"
