(function() {var implementors = {};
implementors['protobuf'] = [];implementors['ql2'] = ["impl <a class='trait' href='protobuf/clear/trait.Clear.html' title='protobuf::clear::Clear'>Clear</a> for <a class='struct' href='ql2/proto/struct.VersionDummy.html' title='ql2::proto::VersionDummy'>VersionDummy</a>","impl <a class='trait' href='protobuf/clear/trait.Clear.html' title='protobuf::clear::Clear'>Clear</a> for <a class='struct' href='ql2/proto/struct.Query.html' title='ql2::proto::Query'>Query</a>","impl <a class='trait' href='protobuf/clear/trait.Clear.html' title='protobuf::clear::Clear'>Clear</a> for <a class='struct' href='ql2/proto/struct.Query_AssocPair.html' title='ql2::proto::Query_AssocPair'>Query_AssocPair</a>","impl <a class='trait' href='protobuf/clear/trait.Clear.html' title='protobuf::clear::Clear'>Clear</a> for <a class='struct' href='ql2/proto/struct.Frame.html' title='ql2::proto::Frame'>Frame</a>","impl <a class='trait' href='protobuf/clear/trait.Clear.html' title='protobuf::clear::Clear'>Clear</a> for <a class='struct' href='ql2/proto/struct.Backtrace.html' title='ql2::proto::Backtrace'>Backtrace</a>","impl <a class='trait' href='protobuf/clear/trait.Clear.html' title='protobuf::clear::Clear'>Clear</a> for <a class='struct' href='ql2/proto/struct.Response.html' title='ql2::proto::Response'>Response</a>","impl <a class='trait' href='protobuf/clear/trait.Clear.html' title='protobuf::clear::Clear'>Clear</a> for <a class='struct' href='ql2/proto/struct.Datum.html' title='ql2::proto::Datum'>Datum</a>","impl <a class='trait' href='protobuf/clear/trait.Clear.html' title='protobuf::clear::Clear'>Clear</a> for <a class='struct' href='ql2/proto/struct.Datum_AssocPair.html' title='ql2::proto::Datum_AssocPair'>Datum_AssocPair</a>","impl <a class='trait' href='protobuf/clear/trait.Clear.html' title='protobuf::clear::Clear'>Clear</a> for <a class='struct' href='ql2/proto/struct.Term.html' title='ql2::proto::Term'>Term</a>","impl <a class='trait' href='protobuf/clear/trait.Clear.html' title='protobuf::clear::Clear'>Clear</a> for <a class='struct' href='ql2/proto/struct.Term_AssocPair.html' title='ql2::proto::Term_AssocPair'>Term_AssocPair</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
